---
title: "Test"
author: "Yubo Wang"
date: "11/1/2016"
output: html_document
---

```{r setup, include=FALSE, echo=FALSE, message=FALSE}
# install.packages("plotly")
library(knitr)
library(plotly)

```

# Choropleth Map:  
This map shows will show us the GDP of every country in the world in 2014. This map will allow interactive functions, such as hovering over the country and getting a response. Also, The map is color coded beased on the GDP, from dark to light.

```{r map, echo=FALSE}
df <- read.csv('https://raw.githubusercontent.com/plotly/datasets/master/2014_world_gdp_with_codes.csv')

# light grey boundaries
l <- list(color = toRGB("grey"), width = 0.5)

# specify map projection/options
g <- list(
  showframe = FALSE,
  showcoastlines = FALSE,
  projection = list(type = 'Mercator')
)

plot_geo(df) %>%
  add_trace(
    z = ~GDP..BILLIONS., color = ~GDP..BILLIONS., colors = 'Blues',
    text = ~COUNTRY, locations = ~CODE, marker = list(line = l)
  ) %>%
  colorbar(title = 'GDP Billions US$', tickprefix = '$') %>%
  layout(
    title = '2014 Global GDP<br>Source:<a href="https://www.cia.gov/library/publications/the-world-factbook/fields/2195.html">CIA World Factbook</a>',
    geo = g
  )
```